[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Uncomment if you need to use Next.js Image Optimization with Netlify
# [[plugins]]
#   package = "@netlify/plugin-nextjs" 